// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDh0I04S07g0eTBbcvY_L3NZvCGuLD6cU',
    appId: '1:823548970866:web:c8113eda7c8ff0cebf7feb',
    messagingSenderId: '823548970866',
    projectId: 'water-app-example',
    authDomain: 'water-app-example.firebaseapp.com',
    storageBucket: 'water-app-example.appspot.com',
    measurementId: 'G-X6C3293DQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGE7c20CuIK28WqqXTKlfJxQEJRe-g9Ws',
    appId: '1:823548970866:android:dd3336796f1fe9cdbf7feb',
    messagingSenderId: '823548970866',
    projectId: 'water-app-example',
    storageBucket: 'water-app-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BJXqsb1eKG_i841LJpV2t2KSQGhKjJY',
    appId: '1:823548970866:ios:819d77c1bdeca72fbf7feb',
    messagingSenderId: '823548970866',
    projectId: 'water-app-example',
    storageBucket: 'water-app-example.appspot.com',
    iosClientId: '823548970866-7ka4usrtti0l2h6plvh7nae3urg42ier.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamidyeWaterExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9BJXqsb1eKG_i841LJpV2t2KSQGhKjJY',
    appId: '1:823548970866:ios:703e4cd1a7160938bf7feb',
    messagingSenderId: '823548970866',
    projectId: 'water-app-example',
    storageBucket: 'water-app-example.appspot.com',
    iosClientId: '823548970866-vhkd5vome2k8lntfvp2ob77dcmpm6k04.apps.googleusercontent.com',
    iosBundleId: 'com.example.hamidyeWaterExample.RunnerTests',
  );
}
